DATASET:
  BATCH_SIZE: 64
  CROP_FACTOR: 0.5
  CROP_PROB: 0.0
  DATASETS_AND_RATIOS: 3dpw-train-smplx_agora-bfh_agora-body_static-hdri-zoomed
  IMG_RES: 224
  MESH_COLOR: pinkish
  NOISE_FACTOR: 0.4
  NUM_WORKERS: 32
  PIN_MEMORY: true
  SCALE_FACTOR: 0.0
  SHUFFLE_TRAIN: true
  VAL_DS: 3dpw-test-cam
  CROP_PERCENT: 0.8
  ALB: false
EXP_NAME: bedlam_cam_ready
LOG_DIR: logs
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
MODEL:
  BACKBONE: hrnet_w48-conv
  BETA_LOSS_WEIGHT: 0.001
  JOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 1.0
TESTING:
  FP_VIS: false
  MESH_VIS: false
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  MAX_EPOCHS: 200000
  PRETRAINED_CKPT: coco
  PRETRAINED_LIT: null
  RELOAD_DATALOADERS_EVERY_EPOCH: false
  RESUME: null
  TEST_BEFORE_TRAINING: false
  WP_VIS: false
  reduce_lr: true
TRIAL:
  bedlam_bbox: true
  criterion: mse
  finetune_3dpw: true

